"""initial schema

Revision ID: d5bd684e2818
Revises: 
Create Date: 2026-02-25 13:38:49.370933
"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import pgvector
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd5bd684e2818'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "postgis"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cost_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost_krw', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cost_logs_date', 'cost_logs', ['created_at'], unique=False)
    op.create_index('idx_cost_logs_provider', 'cost_logs', ['provider'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('entity_type', sa.String(length=16), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
    sa.Column('model', sa.String(length=64), server_default=sa.text("'text-embedding-3-small'"), nullable=False),
    sa.Column('text_hash', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('place', 'note', 'source')", name='ck_embeddings_entity_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_embeddings_entity_type_entity_id')
    )
    op.create_index('idx_embeddings_vector', 'embeddings', ['vector'], unique=False, postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.create_table('ontology_nodes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('namespace', sa.String(length=32), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("namespace IN ('cuisine', 'mood', 'situation', 'companion', 'feature')", name='ck_ontology_nodes_namespace'),
    sa.ForeignKeyConstraint(['parent_id'], ['ontology_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'namespace', name='uq_ontology_nodes_name_namespace')
    )
    op.create_index('idx_ontology_namespace', 'ontology_nodes', ['namespace'], unique=False)
    op.create_index('idx_ontology_parent', 'ontology_nodes', ['parent_id'], unique=False)
    op.create_table('places',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('canonical_name', sa.Text(), nullable=False),
    sa.Column('normalized_name', sa.Text(), nullable=False),
    sa.Column('address_road', sa.Text(), nullable=True),
    sa.Column('address_jibun', sa.Text(), nullable=True),
    sa.Column('region_depth1', sa.Text(), nullable=True),
    sa.Column('region_depth2', sa.Text(), nullable=True),
    sa.Column('region_depth3', sa.Text(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('category_primary', sa.Text(), nullable=True),
    sa.Column('category_secondary', sa.Text(), nullable=True),
    sa.Column('parking', sa.Boolean(), nullable=True),
    sa.Column('reservation', sa.String(length=32), nullable=True),
    sa.Column('price_range', sa.String(length=32), nullable=True),
    sa.Column('mood', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('companions', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('situations', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('user_rating', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("price_range IN ('cheap', 'moderate', 'expensive', 'very_expensive', 'unknown')", name='ck_places_price_range'),
    sa.CheckConstraint("reservation IN ('available', 'required', 'unavailable', 'unknown')", name='ck_places_reservation'),
    sa.CheckConstraint('user_rating BETWEEN 1 AND 5', name='ck_places_user_rating'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_places_category', 'places', ['category_primary', 'category_secondary'], unique=False)
    op.create_index('idx_places_location', 'places', ['location'], unique=False, postgresql_using='gist')
    op.create_index('idx_places_normalized_name', 'places', ['normalized_name'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.create_table('tags',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), server_default=sa.text("'freeform'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('freeform', 'system')", name='ck_tags_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('media',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), server_default=sa.text("'image'"), nullable=False),
    sa.Column('storage_url', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('place_tags',
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('place_id', 'tag_id')
    )
    op.create_table('provider_links',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=16), nullable=False),
    sa.Column('provider_place_id', sa.Text(), nullable=True),
    sa.Column('provider_url', sa.Text(), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("provider IN ('NAVER', 'KAKAO', 'GOOGLE', 'ETC')", name='ck_provider_links_provider'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id', 'provider', name='uq_provider_links_place_provider')
    )
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('URL', 'TEXT', 'IMAGE', 'REVIEW_SNIPPET')", name='ck_sources_type'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('place_id', sa.UUID(), nullable=False),
    sa.Column('visited_at', sa.Date(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=True),
    sa.Column('with_whom', sa.Text(), nullable=True),
    sa.Column('situation', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('revisit', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_visits_rating'),
    sa.ForeignKeyConstraint(['place_id'], ['places.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('from_entity_type', sa.String(length=32), nullable=False),
    sa.Column('from_entity_id', sa.UUID(), nullable=False),
    sa.Column('to_entity_type', sa.String(length=32), nullable=False),
    sa.Column('to_entity_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Float(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('evidence_source_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence BETWEEN 0 AND 1', name='ck_relations_confidence'),
    sa.ForeignKeyConstraint(['evidence_source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_relations_from', 'relations', ['from_entity_type', 'from_entity_id'], unique=False)
    op.create_index('idx_relations_to', 'relations', ['to_entity_type', 'to_entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_relations_to', table_name='relations')
    op.drop_index('idx_relations_from', table_name='relations')
    op.drop_table('relations')
    op.drop_table('visits')
    op.drop_table('sources')
    op.drop_table('provider_links')
    op.drop_table('place_tags')
    op.drop_table('notes')
    op.drop_table('media')
    op.drop_table('tags')
    op.drop_index('idx_places_normalized_name', table_name='places', postgresql_using='gin', postgresql_ops={'normalized_name': 'gin_trgm_ops'})
    op.drop_index('idx_places_location', table_name='places', postgresql_using='gist')
    op.drop_index('idx_places_category', table_name='places')
    op.drop_table('places')
    op.drop_index('idx_ontology_parent', table_name='ontology_nodes')
    op.drop_index('idx_ontology_namespace', table_name='ontology_nodes')
    op.drop_table('ontology_nodes')
    op.drop_index('idx_embeddings_vector', table_name='embeddings', postgresql_using='hnsw', postgresql_ops={'vector': 'vector_cosine_ops'})
    op.drop_table('embeddings')
    op.drop_index('idx_cost_logs_provider', table_name='cost_logs')
    op.drop_index('idx_cost_logs_date', table_name='cost_logs')
    op.drop_table('cost_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
